version: '3.9'

# remember that PV may need to be deleted after certain config changes
services:
  postgres:
    profiles:
      - global
    env_file:
      - ./.env
    # rebuild container if YAML is edited
    build:
      context: .
      dockerfile: Dockerfile.postgres
    develop:
      watch:
        - action: rebuild
          path: ./docker-compose.yml
    image: postgres:16
    container_name: postgres_reservation
    restart: always  
    # .env in same directory
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"  # Map port 5432 on the host to port 5432 in the container.
    volumes:
      - db_data:/var/lib/postgresql/data 
  pgadmin:
    profiles:
      - global
    build:
      context: .
      dockerfile: Dockerfile.pgadmin
    develop:
      watch:
        - action: rebuild
          path: ./docker-compose.yml
    image: dpage/pgadmin4:8.14.0
    container_name: pgadmin_reservation
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}
    ports:
      - "5050:80"
    logging:
      driver: "none"
    depends_on:
      - postgres
  nginx-dev-http:
    profiles:
      - dev
    env_file:
      - ./.env
    build:
      context: ./
      dockerfile: Dockerfile.nginx
    container_name: nginx_reservation_dev
    image: nginx:alpine # alpine for performance
    depends_on:
      - postgres
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/default-dev.conf:/etc/nginx/conf.d/default.conf
    extra_hosts: 
      - "host.docker.internal:host-gateway" # necessary for this to work on Linux
  # environment-specific service
  nginx-prod-https:
    profiles:
      - prod
    env_file:
      - ./.env
    build:
      context: ./
      dockerfile: Dockerfile.nginx
    container_name: nginx_reservation_prod
    image: nginx:alpine # alpine for performance
    depends_on:
      - postgres
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d/default-prod.conf:/etc/nginx/conf.d/default.conf
      - ${SSL_CERT_PATH}:/etc/nginx/ssl/cert.pem
      - ${SSL_KEY_PATH}:/etc/nginx/ssl/key.key
    extra_hosts: 
      - "host.docker.internal:host-gateway" # necessary for this to work on Linux
    environment:
      ALLOWED_IP: ${ALLOWED_IP}
    # necessary for ALLOWED_IP to be written to conf file
    entrypoint: /bin/sh -c "envsubst '\$${ALLOWED_IP}' < /etc/nginx/templates/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

# default docker volume config
volumes:
  db_data: