version: '3.9'

# remember that PV may need to be deleted after certain config changes
services:
  postgres:
    env_file:
      - ./.env
    # rebuild container if YAML is edited
    build:
      context: .
      dockerfile: Dockerfile.postgres
    develop:
      watch:
        - action: rebuild
          path: ./docker-compose.yml
    image: postgres:16
    container_name: reservation_postgres
    restart: always  
    # .env in same directory
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"  # Map port 5432 on the host to port 5432 in the container.
    volumes:
      - db_data:/var/lib/postgresql/data 
  pgadmin:
    build:
      context: .
      dockerfile: Dockerfile.pgadmin
    develop:
      watch:
        - action: rebuild
          path: ./docker-compose.yml
    image: dpage/pgadmin4:8.14.0
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}
    ports:
      - "5050:80"
    logging:
      driver: "none"
    depends_on:
      - postgres
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
    container_name: reservation_nginx
    image: nginx:alpine # alpine for performance
    depends_on:
      - postgres
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

# default docker volume config
volumes:
  db_data: